### STEP 1: IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd

### STEP 2: LOAD DATASET

In [3]:
df=pd.read_csv(r"marketing_campaign_performance_10000.csv")
df.head()

,CampaignID,StartDate,EndDate,Channel,Impressions,Clicks,Leads,Conversions,Cost_USD,Revenue_USD,ROI
0,CAMP00001,2025-04-13,2025-04-19,Search,293520,23335,11643,5389,1052.39,2236.02,1.12
1,CAMP00002,2025-12-15,2025-12-24,Search,200340,15841,6601,2498,3964.90,11740.15,1.96
2,CAMP00003,2025-09-28,2025-10-06,Email,239365,16478,8043,3397,1000.39,1902.24,0.90
3,CAMP00004,2025-04-17,2025-04-30,Search,156382,2672,1014,342,1252.63,2209.74,0.76
4,CAMP00005,2025-03-13,2025-03-22,Influencer,285472,4155,1521,565,4935.48,14111.31,1.86

### STEP 3: VIEW BASIC STRUCTURE

In [4]:
df.head()

,CampaignID,StartDate,EndDate,Channel,Impressions,Clicks,Leads,Conversions,Cost_USD,Revenue_USD,ROI
0,CAMP00001,2025-04-13,2025-04-19,Search,293520,23335,11643,5389,1052.39,2236.02,1.12
1,CAMP00002,2025-12-15,2025-12-24,Search,200340,15841,6601,2498,3964.90,11740.15,1.96
2,CAMP00003,2025-09-28,2025-10-06,Email,239365,16478,8043,3397,1000.39,1902.24,0.90
3,CAMP00004,2025-04-17,2025-04-30,Search,156382,2672,1014,342,1252.63,2209.74,0.76
4,CAMP00005,2025-03-13,2025-03-22,Influencer,285472,4155,1521,565,4935.48,14111.31,1.86

In [5]:
df.shape

(10000, 11)

In [7]:
print(df.columns)

Index(['CampaignID', 'StartDate', 'EndDate', 'Channel', 'Impressions',
       'Clicks', 'Leads', 'Conversions', 'Cost_USD', 'Revenue_USD', 'ROI'],
      dtype='object')

In [8]:
df.dtypes

CampaignID      object
StartDate       object
EndDate         object
Channel         object
Impressions      int64
Clicks           int64
Leads            int64
Conversions      int64
Cost_USD       float64
Revenue_USD    float64
ROI            float64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CampaignID   10000 non-null  object
 1   StartDate    10000 non-null  object
 2   EndDate      10000 non-null  object
 3   Channel      10000 non-null  object
 4   Impressions  10000 non-null  int64
 5   Clicks       10000 non-null  int64
 6   Leads        10000 non-null  int64
 7   Conversions  10000 non-null  int64
 8   Cost_USD     10000 non-null  float64
 9   Revenue_USD  10000 non-null  float64
 10  ROI          10000 non-null  float64
dtypes: float64(3), int64(4), object(4)
memory usage: 859.5+ KB

### STEP 4: CHECK MISSING VALUES

In [10]:
print("Missing Values Per Column:")
print(df.isnull().sum())

Missing Values Per Column:
CampaignID     0
StartDate      0
EndDate        0
Channel        0
Impressions    0
Clicks         0
Leads          0
Conversions    0
Cost_USD       0
Revenue_USD    0
ROI            0
dtype: int64

### STEP 5: CHECK DUPLICATES

In [11]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

### STEP 6: REMOVE DUPLICATES

In [12]:
df.drop_duplicates(inplace=True)

### STEP 7: HANDLE MISSING VALUES

In [13]:
important_cols = ['Channel', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Cost_USD', 'Revenue_USD']
df.dropna(subset=important_cols, inplace=True)

In [14]:
df['Channel'].fillna("Unknown", inplace=True)

### STEP 8: REMOVE BLANK CHANNEL NAMES

In [15]:
df = df[df['Channel'].str.strip() != ""]

### STEP 9: CHECK INVALID NUMERIC VALUES

In [16]:
df = df[df['Cost_USD'] >= 0] # Negative Spend

In [17]:
df = df[df['Revenue_USD'] >= 0] # Negative Revenue

In [18]:
df = df[df['Impressions'] > 0]  # Zero Impressions

In [19]:
df = df[df['Clicks'] > 0] # Zero Clicks

### STEP 10: CONVERT DATE COLUMNS

In [20]:
df['StartDate'] = pd.to_datetime(df['StartDate'])
df['EndDate'] = pd.to_datetime(df['EndDate'])

### STEP 11: CREATE CAMPAIGN DURATION

In [21]:
df['Campaign_Duration'] = (df['EndDate'] - df['StartDate']).dt.days

### STEP 12: CREATE KPI METRICS

In [ ]:
# CTR (Click through Rate)

In [22]:
df['CTR'] = (df['Clicks'] / df['Impressions']) * 100

In [ ]:
# Conversion Rate

In [23]:
df['Conversion_Rate'] = (df['Conversions'] / df['Clicks']) * 100

In [ ]:
# Lead Rate

In [24]:
df['Lead_Rate'] = (df['Leads'] / df['Clicks']) * 100

In [ ]:
# CPC (Cost Per Click)

In [25]:
df['CPC'] = df['Cost_USD'] / df['Clicks']

In [ ]:
# CPA (Cost per Acquision)

In [26]:
df['CPA'] = df['Cost_USD'] / df['Conversions']

In [ ]:
# ROI (Return on Investment)

In [27]:
df['ROI'] = ((df['Revenue_USD'] - df['Cost_USD']) / df['Cost_USD']) * 100

### STEP 13: HANDLE DIVISION ERRORS

In [28]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

### STEP 14: SAVE CLEANED DATASET

In [29]:
df.to_csv("cleaned_marketing_campaign_data.csv", index=False)

### STEP 15: CHANNEL PERFORMANCE SUMMARY

In [30]:
channel_summary = df.groupby('Channel').agg({
    'Cost_USD': 'sum',
    'Revenue_USD': 'sum',
    'Conversions': 'sum',
    'ROI': 'mean',
    'CPA': 'mean',
    'Conversion_Rate': 'mean'
}).reset_index()

In [31]:
print(channel_summary)

      Channel    Cost_USD  Revenue_USD  Conversions         ROI        CPA  \
0     Display  5343184.30  10715125.21      2057607   99.947846  10.804092
1       Email  5065029.98  10130542.61      2076423  100.996132  10.130729
2  Influencer  5278787.92  10558118.99      2101198   99.736693   9.111069
3      Search  4916568.46   9897677.79      1951752  101.330737  10.894869
4      Social  4919999.25   9725024.70      1920020   98.782186  10.333181

   Conversion_Rate
0        12.111601
1        12.121959
2        11.988883
3        12.114953
4        12.136829

### STEP 16: BEST REVENUE CHANNEL

In [32]:
best_revenue = channel_summary.loc[channel_summary['Revenue_USD'].idxmax()]
print("Highest Revenue Channel:")
print(best_revenue)

Highest Revenue Channel:
Channel                Display
Cost_USD             5343184.3
Revenue_USD        10715125.21
Conversions            2057607
ROI                  99.947846
CPA                  10.804092
Conversion_Rate      12.111601
Name: 0, dtype: object

### STEP 17: BEST ROI CHANNEL

In [33]:
best_roi = channel_summary.loc[channel_summary['ROI'].idxmax()]
print("Highest ROI Channel:")
print(best_roi)

Highest ROI Channel:
Channel                Search
Cost_USD           4916568.46
Revenue_USD        9897677.79
Conversions           1951752
ROI                101.330737
CPA                 10.894869
Conversion_Rate     12.114953
Name: 3, dtype: object

### STEP 18: LOWEST CPA CHANNEL

In [34]:
lowest_cpa = channel_summary.loc[channel_summary['CPA'].idxmin()]
print("Lowest CPA Channel:")
print(lowest_cpa)

Lowest CPA Channel:
Channel             Influencer
Cost_USD            5278787.92
Revenue_USD        10558118.99
Conversions            2101198
ROI                  99.736693
CPA                   9.111069
Conversion_Rate      11.988883
Name: 2, dtype: object

### STEP 19: WORST CHANNEL (Budget Waste)

In [35]:
worst_roi = channel_summary.loc[channel_summary['ROI'].idxmin()]
print("Lowest ROI / Budget Waste Channel:")
print(worst_roi)

Lowest ROI / Budget Waste Channel:
Channel                Social
Cost_USD           4919999.25
Revenue_USD         9725024.7
Conversions           1920020
ROI                 98.782186
CPA                 10.333181
Conversion_Rate     12.136829
Name: 4, dtype: object

### STEP 20: CALCULATE FUNNEL TOTALS

In [36]:
funnel = {
    'Impressions': df['Impressions'].sum(),
    'Clicks': df['Clicks'].sum(),
    'Leads': df['Leads'].sum(),
    'Conversions': df['Conversions'].sum()
}

print("Funnel Totals:")
print(funnel)

Funnel Totals:
{'Impressions': 1522606379, 'Clicks': 83389933, 'Leads': 25124636, 'Conversions': 10107000}

### STEP 21: FUNNEL DROP-OFF RATES

In [37]:
click_drop = (funnel['Clicks'] / funnel['Impressions']) * 100  # Click-through from impressions

In [38]:
lead_drop = (funnel['Leads'] / funnel['Clicks']) * 100 # Leads from clicks

In [39]:
conversion_drop = (funnel['Conversions'] / funnel['Leads']) * 100 # Conversions from leads

In [40]:
print("Click Rate from Impressions:", click_drop)
print("Lead Rate from Clicks:", lead_drop)
print("Conversion Rate from Leads:", conversion_drop)

Click Rate from Impressions: 5.476788627062491
Lead Rate from Clicks: 30.1290996360436
Conversion Rate from Leads: 40.2274484693032

### STEP 22: INTERPRETATION LOGIC

In [41]:
if click_drop < 5:                                         # Example
    print("Poor ad creatives or weak targeting.")
    
if lead_drop < 20:
    print("Landing page optimization needed.")
    
if conversion_drop < 30:
    print("Sales or nurturing process needs improvement.")

### STEP 23: MONTHLY PERFORMANCE ANALYSIS

In [42]:
df['Month'] = df['StartDate'].dt.to_period('M')

monthly_summary = df.groupby('Month').agg({
    'Cost_USD':'sum',
    'Revenue_USD':'sum',
    'Conversions':'sum',
    'ROI':'mean'
}).reset_index()

print(monthly_summary)

      Month    Cost_USD  Revenue_USD  Conversions         ROI
0   2025-01  2121091.56   4321748.75       872983  101.304526
1   2025-02  1958670.98   3917068.44       730725  100.843225
2   2025-03  2163766.51   4355047.85       837286  100.699234
3   2025-04  2270411.89   4583817.85       924076  102.009861
4   2025-05  2250756.51   4533400.94       817599  100.665801
5   2025-06  2086428.79   4080666.52       863365   98.013979
6   2025-07  2138898.24   4239110.66       854471  100.520324
7   2025-08  2185716.06   4390108.74       865415  100.967400
8   2025-09  1993657.74   3960373.22       782284   96.966216
9   2025-10  2146254.38   4363171.95       854254  102.984319
10  2025-11  2131126.44   4173435.66       863923   97.109594
11  2025-12  2076790.81   4108538.72       840619   99.473446

### FINAL OUTPUT FILES

#### Channel summary

In [43]:
channel_summary.to_csv("channel_summary.csv", index=False)

#### Monthly summary

In [44]:
monthly_summary.to_csv("monthly_summary.csv", index=False)